// 第三阶段/day23/day0228(New)/react-pro/src/components/Show.js
import React, {Component} from 'react'

export default class Show extends Component{

    constructor(){
        super();
        this.state = {
            name : '',
            sex :'',
            year : '',
            like :[]
        }
    }

    render(){
        let{name, sex, year, like} = this.state;
        return (
            <div className="show" style={{display:this.props.isShowshow}}>
                <h1>查看</h1>
                <p>姓名：{name}</p>
                <p>性别：{sex}</p>
                <p>出生年份：{year}</p>
                <p>兴趣爱好：{like}</p>
                
                <button onClick={this.finishAction.bind(this)}>查看完成</button>
            </div>
        );
    }

    finishAction(){
        
    }

    componentWillMount(){
    

        this.token = PubSub.subscribe(
            'show1-data',
            (event, param) =>{
                // console.log('监听到了comfirmModify-data')
                // console.log('modifyIndex'+modifyIndex);
                let {name, sex, year, like} = param;
                this.state.name = name;
                this.state.sex = sex;
                this.state.year = year;
                this.state.like = like;
                


        
            }
        )
    }

    finishAction(){
        PubSub.publish(
            'show-change',
            0
        )
    }
}

// 第三阶段/day14/day0201新/vue-pro/src4todolist父子组件传值/components/Show.vue
<template>
<div class="show-card">
	<h1>查看</h1>
	<p>姓名：{{data.name}}</p>
	<p>性别：{{data.sex}}</p>
	<p>出生年份：{{data.year}}</p>
	<p>兴趣爱好：{{data.like}}</p>
	<p>个性签名：{{data.sign}}</p>
	<button @click="finishAction()">查看完成</button>
</div>
</template>

<script>
export default {
	name: 'show-card',
	props: {
		data: Object
	},
	methods: {
		finishAction(){
			this.$emit('show-finish');
		}
	}
}
</script>

<style>
</style>
